import logging
import google.generativeai as genai
from app.core.config import settings
from app.core.exceptions import AppError

logger = logging.getLogger(__name__)

class GeminiService:
    """
    Service responsible for interacting with the Google Gemini API.
    Handles client initialization and content generation.
    """
    def __init__(self):
        if not settings.GEMINI_API_KEY:
            logger.error("GEMINI_API_KEY is not set.")
            raise AppError("AI Service configuration is missing.", status_code=500)
        
        try:
            genai.configure(api_key=settings.GEMINI_API_KEY)
            self.model = genai.GenerativeModel('gemini-2.5-flash')
        except Exception as e:
            logger.error(f"Failed to initialize Gemini API: {e}", exc_info=True)
            raise AppError("Failed to initialize AI Service.", status_code=500)

    def generate_response(self, prompt: str) -> str:
        """
        Sends a prompt to the Gemini model and retrieves the generated text.
        
        Args:
            prompt (str): The combined system and user prompt.
            
        Returns:
            str: The text content generated by the AI.
            
        Raises:
            AppError: If the AI generates an empty response or encounters an API error.
        """
        try:
            logger.info("Sending request to Gemini API.")
            response = self.model.generate_content(prompt)
            if not response.text:
                raise AppError("Received empty response from AI.", status_code=500)
            return response.text
        except AppError:
            raise
        except Exception as e:
            logger.error(f"Gemini generation failed: {e}", exc_info=True)
            raise AppError("Failed to generate response from AI.", status_code=500)
